import turtle
turtle.Screen().bgcolor("black")
turtle.Screen().title = ("square")
turtle.Screen().setup(600,600)
pen = turtle.Turtle()
pen.color("white")
pen.forward(200)
pen.right(90)
pen.forward(200)
pen.right(90)
pen.forward(200)
pen.right(90)
pen.forward(200)
pen.right(90)
turtle.done()